apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-cd-pipeline-
spec:
  entrypoint: ci-cd-pipeline
  templates:
    - name: ci-cd-pipeline
      steps:
        - - name: checkout-code
            template: checkout-code
        - - name: build-image
            template: build-image
        - - name: run-tests
            template: run-tests
        - - name: deploy
            template: deploy-app

    - name: checkout-code
      container:
        image: alpine:latest # 使用 Alpine 镜像作为基础镜像
        command: ["/bin/sh", "-c"] # 执行一个 shell 命令
        args:
          - |
            apk add --no-cache git && git clone https://github.com/qingzhang100/Carousal.git  # 安装 Git 并克隆代码

    - name: build-image
      container:
        image: docker:latest
        command: ["docker", "build", "-t", "your-image", "."]

    - name: run-tests
      container:
        image: your-test-image
        command: ["run", "tests"]

    - name: deploy-app
      container:
        image: kubectl:latest
        command: ["kubectl", "apply", "-f", "deployment.yaml"]
